#!/bin/bash
# Complete Guide to Register Your Agent on AgentBeats

echo "============================================================"
echo "🎯 How to Register Your Agent on AgentBeats"
echo "============================================================"
echo ""

# Check if everything is running
echo "1. Checking if agent is running..."
if curl -s http://localhost:8080/health > /dev/null 2>&1; then
    echo "   ✅ Agent is running"
else
    echo "   ❌ Agent is NOT running"
    echo "   Start it: cd /Users/joe2690812044/Desktop/cs\\ 195/TheAgentCompany/agentbeats_integration && nohup ./run_agent.sh > agent.log 2>&1 &"
    exit 1
fi

echo ""
echo "2. Checking if tunnel is running..."
if ps aux | grep -v grep | grep cloudflared > /dev/null 2>&1; then
    TUNNEL_URL=$(grep -oE "https://[a-z-]+\.trycloudflare\.com" /tmp/cloudflared.log 2>/dev/null | head -1)
    echo "   ✅ Cloudflared tunnel is running"
    echo "   📍 URL: $TUNNEL_URL"
else
    echo "   ❌ Tunnel is NOT running"
    echo "   Start it: cd /tmp && nohup ./cloudflared tunnel --url http://localhost:8080 > cloudflared.log 2>&1 &"
    exit 1
fi

echo ""
echo "============================================================"
echo "✅ Everything is ready! Here's how to register:"
echo "============================================================"
echo ""
echo "METHOD 1: Via Web UI (EASIEST) ⭐"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Open your browser and go to:"
echo "   🌐 https://agentbeats.org"
echo ""
echo "Step 2: Look for one of these:"
echo "   • 'Register Agent' button"
echo "   • 'Add Agent' button"  
echo "   • 'New Agent' link"
echo "   • Go to 'Agents' menu → 'Register' or 'Add'"
echo ""
echo "Step 3: Fill in the registration form:"
echo ""
echo "   ┌─────────────────────────────────────────────────────────┐"
echo "   │ Alias:        TheAgentCompany Benchmark Reporter        │"
echo "   │ Agent URL:    $TUNNEL_URL"
echo "   │ Launcher URL: $TUNNEL_URL"
echo "   │ Type:         Green Agent (check the box)               │"
echo "   │ Timeout:      600                                        │"
echo "   └─────────────────────────────────────────────────────────┘"
echo ""
echo "Step 4: Click 'Submit' or 'Register'"
echo ""
echo "Step 5: Look for your agent in the agents list"
echo ""
echo "Step 6: Create a battle and select your agent"
echo ""
echo "Step 7: Watch the results!"
echo "   Monitor: tail -f /Users/joe2690812044/Desktop/cs\\ 195/TheAgentCompany/agentbeats_integration/agent.log"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "METHOD 2: Via API (Alternative)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run this command:"
echo ""
echo "curl -X POST https://agentbeats.org/api/agents \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"alias\": \"TheAgentCompany Benchmark Reporter\","
echo "    \"agent_url\": \"$TUNNEL_URL\","
echo "    \"launcher_url\": \"$TUNNEL_URL\","
echo "    \"is_green\": true,"
echo "    \"participant_requirements\": [],"
echo "    \"battle_timeout\": 600"
echo "  }'"
echo ""
echo "Note: API registration has been failing with validation errors."
echo "      The UI method is more reliable."
echo ""
echo "============================================================"
echo "📋 Quick Info to Copy/Paste"
echo "============================================================"
echo ""
echo "Backend URL:  https://agentbeats.org"
echo "Agent URL:    $TUNNEL_URL"
echo "Agent Name:   TheAgentCompany Benchmark Reporter"
echo "Type:         Green Agent"
echo "Timeout:      600 seconds"
echo ""
echo "============================================================"
echo "🧪 Test Your Agent Before Registering"
echo "============================================================"
echo ""
echo "# Test agent card endpoint:"
echo "curl $TUNNEL_URL/.well-known/agent-card.json"
echo ""
echo "# Test health endpoint:"
echo "curl $TUNNEL_URL/health"
echo ""
echo "# Test status endpoint:"
echo "curl $TUNNEL_URL/status"
echo ""
echo "============================================================"
echo "❓ Need Help?"
echo "============================================================"
echo ""
echo "If you can't find the registration page:"
echo "1. Try these URLs:"
echo "   • https://agentbeats.org/agents"
echo "   • https://agentbeats.org/dashboard"
echo "   • https://agentbeats.org/app"
echo ""
echo "2. Look in the navigation menu for:"
echo "   • 'Agents'"
echo "   • 'Dashboard'"
echo "   • 'My Agents'"
echo ""
echo "3. You may need to sign in/create an account first"
echo ""
echo "4. Ask your instructor: 'Where is the agent registration page?'"
echo ""
echo "============================================================"
echo "✅ Your agent is ready and waiting for registration!"
echo "============================================================"
